"""
KS Promocionales — Daily Product Scraper
Scrapes catalogospromocionales.com, merges new products into data/products.json,
and updates data/categories.json productCounts.

Run:  python scripts/daily-scraper.py
Deps: pip install requests beautifulsoup4 lxml
"""

import requests
from bs4 import BeautifulSoup
import json
import time
import re
import os
import sys
from urllib.parse import urljoin
from collections import Counter

# ── Config ────────────────────────────────────────────────────────────────────
BASE_URL   = "https://www.catalogospromocionales.com"
DELAY      = 1.5   # seconds between requests
MAX_PAGES  = 50    # max pagination pages per category (safety cap)

ROOT = os.path.join(os.path.dirname(__file__), '..')
PRODUCTS_FILE   = os.path.join(ROOT, 'data', 'products.json')
CATEGORIES_FILE = os.path.join(ROOT, 'data', 'categories.json')

# ── Direct URLs for categories not listed on the subcategories discovery page ──
# These are always scraped regardless of what get_all_categories() finds.
# For precio-bomba: Catalogo URL (start page 1, scraper handles pagination)
DIRECT_CATEGORY_URLS = {
    'precio-bomba':   f'{BASE_URL}/Catalogo/Default.aspx?id=434',
    'antiestres':     f'{BASE_URL}/promocionales/antiestres.html',
    'antimicrobianos':f'{BASE_URL}/promocionales/antimicrobianos.html',
    'reflectivos':    f'{BASE_URL}/promocionales/reflectivos.html',
    'bar-y-vino':     f'{BASE_URL}/promocionales/bar-y-vino.html',
    'bicicleta':      f'{BASE_URL}/promocionales/bicicleta.html',
    'calculadoras':   f'{BASE_URL}/promocionales/calculadoras.html',
    'deportes':       f'{BASE_URL}/promocionales/deportes.html',
    'econature':      f'{BASE_URL}/promocionales/econature.html',
    'golf':           f'{BASE_URL}/promocionales/golf.html',
    'gorras':         f'{BASE_URL}/promocionales/gorras.html',
    'iluminacion':    f'{BASE_URL}/promocionales/iluminacion.html',
    'infantil':       f'{BASE_URL}/promocionales/infantil.html',
    'juegos':         f'{BASE_URL}/promocionales/juegos.html',
    'master-line':    f'{BASE_URL}/promocionales/master-line.html',
    'medicos':        f'{BASE_URL}/promocionales/medicos.html',
    'memorias-usb':   f'{BASE_URL}/promocionales/memorias-usb.html',
    'relojes':        f'{BASE_URL}/promocionales/relojes.html',
}

# ── Category mapping: scraped slug → our category ID ──────────────────────────
# Keys are generated by slugifying the category name from the site
CATEGORY_MAP = {
    # Mugs / Vasos / Termos
    'mugs':                   'mugs',
    'mugs-vasos-termos':      'mugs',
    'termos':                 'mugs',
    'vasos':                  'mugs',
    # Escritura
    'escritura':              'escritura',
    'articulos-de-escritura': 'escritura',
    'lapiceros':              'escritura',
    'boligrafos':             'escritura',
    # Tecnología
    'tecnologia':             'tecnologia',
    'tecnologia-y-gadgets':   'tecnologia',
    'gadgets':                'tecnologia',
    'memorias-usb':           'memorias-usb',
    'usb':                    'memorias-usb',
    # Hogar
    'hogar':                  'hogar',
    'cocina':                 'hogar',
    # Oficina
    'oficina':                'oficina',
    'articulos-de-oficina':   'oficina',
    # Herramientas
    'herramientas':           'herramientas',
    # Llaveros
    'llaveros':               'llaveros',
    # Paraguas
    'paraguas':               'paraguas',
    'sombrillas':             'paraguas',
    # Variedades
    'variedades':             'variedades',
    # Novedades
    'novedades':              'novedades',
    # Antiestrés
    'antiestres':             'antiestres',
    'anti-estres':            'antiestres',
    'antistress':             'antiestres',
    # Maletines / Bolsos
    'maletines':              'maletines',
    'bolsos-mochilas':        'maletines',
    'bolsos':                 'maletines',
    'mochilas':               'maletines',
    'maletines-y-bolsos':     'maletines',
    # Cuidado Personal
    'cuidado-personal':       'cuidado-personal',
    'pharma-cuidado-personal':'cuidado-personal',
    'pharma':                 'cuidado-personal',
    # Ecología
    'ecologia':               'ecologia',
    'ecologicos':             'ecologia',
    'ecologico':              'ecologia',
    'eco':                    'ecologia',
    'econature':              'econature',
    # Automóvil
    'automovil':              'automovil',
    'accesorios-auto':        'automovil',
    'auto':                   'automovil',
    'accesorios-para-auto':   'automovil',
    # Confección / Textiles
    'confeccion':             'confeccion',
    'textiles':               'confeccion',
    'ropa':                   'confeccion',
    # Deportes
    'deportes':               'deportes',
    'deporte':                'deportes',
    # Gorras
    'gorras':                 'gorras',
    'gorras-y-sombreros':     'gorras',
    # Infantil
    'infantil':               'infantil',
    'ninos':                  'infantil',
    # Juegos
    'juegos':                 'juegos',
    # Golf
    'golf':                   'golf',
    # Reflectivos
    'reflectivos':            'reflectivos',
    # Bicicleta
    'bicicleta':              'bicicleta',
    'bici':                   'bicicleta',
    # Calculadoras
    'calculadoras':           'calculadoras',
    # Antimicrobianos
    'antimicrobianos':        'antimicrobianos',
    'antibacterial':          'antimicrobianos',
    # Master Line
    'master-line':            'master-line',
    'masterline':             'master-line',
    # Médicos
    'medicos':                'medicos',
    'salud':                  'medicos',
    # Iluminación
    'iluminacion':            'iluminacion',
    'iluminacion-y-linternas':'iluminacion',
    # Producción Nacional
    'produccion-nacional':    'produccion-nacional',
    'nacional':               'produccion-nacional',
    # Relojes
    'relojes':                'relojes',
    # Precio Bomba
    'precio-bomba':           'precio-bomba',
    'oferta':                 'precio-bomba',
    'ofertas':                'precio-bomba',
    'bar-y-vino':             'bar-y-vino',
    'bar':                    'bar-y-vino',
    'vino':                   'bar-y-vino',
}

VALID_CATEGORY_IDS = set(CATEGORY_MAP.values())

SESSION = requests.Session()
SESSION.headers.update({
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'Accept-Language': 'es-EC,es;q=0.9',
})


# ── Helpers ───────────────────────────────────────────────────────────────────

def slugify(text):
    text = text.lower().strip()
    for src, dst in [('á','a'),('é','e'),('í','i'),('ó','o'),('ú','u'),('ñ','n'),('ü','u')]:
        text = text.replace(src, dst)
    text = re.sub(r'[^a-z0-9\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'-+', '-', text)
    return text.strip('-')


def get_page(url, retries=3):
    for attempt in range(retries):
        try:
            r = SESSION.get(url, timeout=20)
            r.raise_for_status()
            return r.text
        except Exception as e:
            if attempt == retries - 1:
                print(f"  [ERROR] {url}: {e}")
                return None
            time.sleep(3)
    return None


def extract_product_id_from_image(img_url):
    """Extract numeric ID from image URL like /images/productos/12345.jpg"""
    m = re.search(r'/productos/(\d+)', img_url)
    return m.group(1) if m else None


def map_category(raw_name):
    """Map a raw category name from the site to our category ID."""
    slug = slugify(raw_name)
    # Direct lookup
    if slug in CATEGORY_MAP:
        return CATEGORY_MAP[slug]
    # Partial match: check if any key is contained in the slug
    for key, val in CATEGORY_MAP.items():
        if key in slug or slug in key:
            return val
    return None


def build_product(name, img_url, product_url, category_id):
    """Build a product dict in the format expected by Next.js."""
    clean_name = re.sub(r'\s+', ' ', name).strip()
    # Capitalise each word
    clean_name = ' '.join(
        w.capitalize() if len(w) > 2 else w.lower()
        for w in clean_name.split()
    )

    prod_id = extract_product_id_from_image(img_url)
    name_slug = slugify(clean_name)
    # Slug must be globally unique across all categories to avoid static-route collisions.
    # Use the numeric product ID from the image URL when available (most reliable).
    slug = f"{name_slug}-{prod_id}" if prod_id else f"{category_id}-{name_slug}"
    unique_id = f"{category_id}-{prod_id}" if prod_id else f"{category_id}-{name_slug}"[:80]

    return {
        'id': unique_id,
        'name': clean_name,
        'slug': slug,
        'categoryId': category_id,
        'shortDescription': f'{clean_name} personalizado con tu logo corporativo. '
                            f'Ideal para regalos empresariales y campañas promocionales.',
        'story': f'Destaca tu marca con {clean_name}, un artículo promocional de calidad '
                 f'que tus clientes conservarán. Personalización incluida sin costo adicional.',
        'features': [
            'Personalización con tu logo o mensaje',
            'Calidad premium garantizada',
            'Entrega en Ecuador y Colombia',
            'Cotización sin compromiso',
        ],
        'images': [img_url],
        'whatsappMessage': f'Hola, me interesa cotizar: {clean_name}. '
                           f'¿Podrían enviarme información sobre personalización y precios?',
        'seoTitle': f'{clean_name} Personalizado | KS Promocionales Ecuador',
        'seoDescription': f'{clean_name} personalizado con tu logo en Ecuador. '
                          f'Calidad premium, entrega rápida y cotización gratuita.',
        'keywords': f'{clean_name.lower()}, regalo corporativo, artículo promocional, '
                    f'producto personalizado Ecuador',
        'useCases': ['regalos empresariales', 'campañas publicitarias', 'eventos corporativos'],
        'featured': False,
        'bestseller': False,
    }


# ── Scraping ──────────────────────────────────────────────────────────────────

def get_all_categories():
    """Return list of (name, url) tuples from the subcategories page."""
    html = get_page(f"{BASE_URL}/seccion/subcategorias.html")
    if not html:
        return []

    soup = BeautifulSoup(html, 'lxml')
    seen = set()
    cats = []

    for link in soup.find_all('a', href=True):
        href = link['href']
        text = link.get_text(strip=True)
        if not text or len(text) < 3:
            continue
        if '/promocionales/' not in href and '/seccion/' not in href:
            continue
        if href == '/seccion/subcategorias.html':
            continue

        full_url = urljoin(BASE_URL, href)
        key = (text.lower(), full_url)
        if key not in seen:
            seen.add(key)
            cats.append((text, full_url))

    return cats


def find_next_page_url(soup, current_page):
    """
    Extract the URL for the next page from pagination links.
    catalogospromocionales.com uses /Catalogo/Default.aspx?id=XX&Page=N
    """
    next_page_num = str(current_page + 1)

    # Find all links with Page= parameter
    page_links = soup.find_all('a', href=re.compile(r'[Pp]age=\d+'))
    for link in page_links:
        href = link.get('href', '')
        m = re.search(r'[Pp]age=(\d+)', href)
        if m and m.group(1) == next_page_num:
            return urljoin(BASE_URL, href)

    # Fallback: text-based next link (›, », siguiente, next)
    next_link = soup.find('a', string=re.compile(r'siguiente|next|[›»>]', re.I))
    if next_link and next_link.get('href'):
        return urljoin(BASE_URL, next_link['href'])

    return None


def scrape_category_products(cat_name, cat_url, forced_category_id=None):
    """Scrape all products from a category, handling pagination."""
    category_id = forced_category_id or map_category(cat_name)
    if not category_id:
        print(f"  [SKIP] No category mapping for '{cat_name}'")
        return []

    products = []
    seen_imgs = set()
    current_url = cat_url
    page = 1

    while page <= MAX_PAGES:
        html = get_page(current_url)
        if not html:
            break

        soup = BeautifulSoup(html, 'lxml')
        found_on_page = 0

        def normalise_img(src):
            url = urljoin(BASE_URL, src)
            return ('https:' + url) if url.startswith('//') else url

        def clean_name(raw):
            """Strip reference codes and '[Más]' suffix from product names."""
            name = re.sub(r'\[.*?\]', '', raw)          # remove [Más], [+], etc.
            name = re.sub(r'\s*-\s*PRECIO BOMBA\s*', '', name, flags=re.I)
            name = re.sub(r'\s+', ' ', name).strip()
            return name

        # ── Primary: #backTable → div.itemProducto- (works for both /promocionales/ and /Catalogo/) ──
        back_table = soup.find(id='backTable')
        items = back_table.find_all('div', class_='itemProducto-') if back_table else []

        if items:
            for item in items:
                link = item.find('a', class_='img-producto')
                if not link:
                    continue
                img = link.find('img')
                if not img:
                    continue
                img_src = img.get('src') or img.get('data-src', '')
                if not img_src:
                    continue
                img_url = normalise_img(img_src)
                if img_url in seen_imgs:
                    continue

                # Name: prefer alt (cleanest), fall back to h3
                name = clean_name(img.get('alt', '').strip())
                if not name or len(name) < 3:
                    h3 = item.find('h3')
                    name = clean_name(h3.get_text(strip=True)) if h3 else ''
                if not name or len(name) < 3:
                    continue

                seen_imgs.add(img_url)
                p = build_product(name, img_url, current_url, category_id)
                products.append(p)
                found_on_page += 1

        else:
            # Fallback: find all full-size product images directly (/productos/XXXX, not /productos-s/)
            for img in soup.find_all('img', src=re.compile(r'/images/productos/\d+', re.I)):
                img_url = normalise_img(img['src'])
                if img_url in seen_imgs:
                    continue
                name = clean_name(img.get('alt', '').strip())
                if not name or len(name) < 3:
                    parent = img.find_parent(['a', 'td', 'div', 'li'])
                    if parent:
                        h3 = parent.find(['h3', 'h4', 'h2', 'strong', 'b'])
                        if h3:
                            name = clean_name(h3.get_text(strip=True))
                if name and len(name) >= 3:
                    seen_imgs.add(img_url)
                    p = build_product(name, img_url, current_url, category_id)
                    products.append(p)
                    found_on_page += 1

        print(f"    page {page}: {found_on_page} products")

        if found_on_page == 0:
            break

        next_url = find_next_page_url(soup, page)
        if not next_url:
            break

        current_url = next_url
        page += 1
        time.sleep(DELAY)

    return products


# ── Merge & Save ─────────────────────────────────────────────────────────────

def merge_products(existing, new_products, force_category=False):
    """
    Merge new_products into existing list, deduplicating by image URL.

    When force_category=True (used for direct-URL scrapes where we know
    the exact category), existing products whose image URL matches are
    updated to the new categoryId rather than skipped.  This fixes the case
    where a product was previously scraped under a wrong/generic category.
    """
    # Build a map: image_url → index in existing list
    img_to_idx = {}
    for idx, p in enumerate(existing):
        for img in p.get('images', []):
            img_to_idx[img] = idx

    added = 0
    reassigned = 0
    for p in new_products:
        imgs = p.get('images', [])
        if not imgs:
            continue
        img0 = imgs[0]
        if img0 in img_to_idx:
            if force_category:
                existing_p = existing[img_to_idx[img0]]
                if existing_p['categoryId'] != p['categoryId']:
                    existing_p['categoryId'] = p['categoryId']
                    existing_p['id'] = p['id']
                    existing_p['slug'] = p['slug']
                    reassigned += 1
        else:
            existing.append(p)
            img_to_idx[img0] = len(existing) - 1
            added += 1

    if reassigned:
        print(f"  Reassigned category for {reassigned} existing products")
    return existing, added


def update_category_counts(products, categories):
    counts = Counter(p['categoryId'] for p in products)
    for cat in categories:
        cat['productCount'] = counts.get(cat['id'], 0)
    return categories


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("KS Promocionales — Daily Scraper")
    print("=" * 60)

    # Load existing data
    with open(PRODUCTS_FILE, encoding='utf-8') as f:
        existing_products = json.load(f)
    with open(CATEGORIES_FILE, encoding='utf-8') as f:
        categories = json.load(f)

    print(f"Existing products: {len(existing_products)}")

    all_new = []
    scraped_urls = set()  # track URLs we've already scraped to avoid double-work

    # ── Step 1: Always scrape the hardcoded direct URLs ───────────────────────
    # force_category=True: reassign existing products to the correct category.
    print(f"\nScraping {len(DIRECT_CATEGORY_URLS)} hardcoded category URLs...")
    direct_products = []
    for idx, (cat_id, cat_url) in enumerate(DIRECT_CATEGORY_URLS.items(), 1):
        print(f"\n[direct {idx}/{len(DIRECT_CATEGORY_URLS)}] {cat_id} <- {cat_url}")
        products = scrape_category_products(cat_id, cat_url, forced_category_id=cat_id)
        direct_products.extend(products)
        scraped_urls.add(cat_url)
        print(f"  Subtotal: {len(products)} scraped")
        time.sleep(DELAY)

    # Merge direct products with force_category so existing products get reassigned
    existing_products, direct_added = merge_products(existing_products, direct_products, force_category=True)
    print(f"\nDirect scrape — new: {direct_added}, total now: {len(existing_products)}")

    # ── Step 2: Auto-discover remaining categories ────────────────────────────
    print("\nFetching auto-discovered category list...")
    all_cats = get_all_categories()
    print(f"Found {len(all_cats)} categories via discovery")

    for idx, (name, url) in enumerate(all_cats, 1):
        if url in scraped_urls:
            print(f"\n[auto {idx}/{len(all_cats)}] {name} -> already scraped, skipping")
            continue
        cat_id = map_category(name)
        print(f"\n[auto {idx}/{len(all_cats)}] {name} -> {cat_id or 'SKIP'}")
        if not cat_id:
            continue
        products = scrape_category_products(name, url)
        all_new.extend(products)
        scraped_urls.add(url)
        print(f"  Subtotal: {len(products)} scraped")
        time.sleep(DELAY)

    print(f"\nAuto-discovery scraped: {len(all_new)}")

    # Merge auto-discovered (no force_category — don't override direct assignments)
    existing_products, auto_added = merge_products(existing_products, all_new)
    print(f"Auto-discovery — new: {auto_added}, total now: {len(existing_products)}")
    merged = existing_products
    added = direct_added + auto_added
    print(f"\nTotal new products added: {added}")
    print(f"Total products now: {len(merged)}")

    # Update counts
    categories = update_category_counts(merged, categories)

    # Save
    with open(PRODUCTS_FILE, 'w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    with open(CATEGORIES_FILE, 'w', encoding='utf-8') as f:
        json.dump(categories, f, ensure_ascii=False, indent=2)

    print("\nSaved data/products.json and data/categories.json")

    # Summary
    print("\nCategory breakdown:")
    counts = Counter(p['categoryId'] for p in merged)
    for cat_id, count in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {cat_id:<30} {count:>5}")

    print("\nDone.")


if __name__ == '__main__':
    main()
